[config]
default_to_workspace = false

[tasks.default]
run_task = { name = ["format", "lint"], parallel = true }

[tasks.all]
run_task = { name = ["format", "lint", "test"], parallel = true }

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-Dwarnings"]

[tasks.build]
command = "cargo"
args = ["build", "--all-targets"]

[tasks.test]
command = "cargo"
args = ["test", "--all"]
