[config]
skip_core_tasks = true

[tasks.default]
run_task = { name = ["format", "lint"], parallel = true }

[tasks.all]
run_task = { name = ["format", "lint", "test-all"], parallel = true }

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-Dwarnings"]

[tasks.build]
command = "cargo"
args = ["build", "--all-targets"]

[tasks.test-all]
run_task = { name = ["test", "python-e2e"] }

[tasks.test]
command = "cargo"
args = ["test", "--all"]

[tasks.python-e2e]
script_runner = "@shell"
script = '''
pushd python_e2e && makers test && popd
'''
