[config]
skip_core_tasks = true

[env]
TARPAULIN_COMMON_ARGS = "tarpaulin --all-features --timeout 120 --skip-clean"

[tasks.default]
run_task = { name = ["format", "lint"], parallel = true }

[tasks.all]
run_task = { name = ["format", "lint", "test-all"], parallel = true }

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-Dwarnings"]

[tasks.build]
command = "cargo"
args = ["build", "--all-targets"]

[tasks.check]
command = "cargo"
args = ["check", "--all-targets", "--all-features"]

[tasks.fetch]
command = "cargo"
args = ["fetch"]

[tasks.install-nextest]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
    "nextest",
    "--help",
] }

[tasks.install-tarpaulin]
install_crate = { crate_name = "cargo-tarpaulin", binary = "cargo", test_arg = [
    "tarpaulin",
    "--help",
] }

[tasks.cov-clean]
command = "cargo"
args = ["clean"]

[tasks.test-all]
run_task = { name = ["test", "python-e2e"] }

[tasks.test]
command = "cargo"
args = ["test", "--all"]

[tasks.test-cov]
dependencies = ["install-tarpaulin", "cov-clean"]
command = "cargo"
args = ["@@split(TARPAULIN_COMMON_ARGS, )"]

[tasks.cov-html]
dependencies = ["install-tarpaulin", "cov-clean"]
command = "cargo"
args = ["@@split(TARPAULIN_COMMON_ARGS, )", "--out", "Html"]

[tasks.python-e2e]
script_runner = "@shell"
script = '''
pushd python_e2e && makers test && popd
'''

[tasks.clippy-ci]
command = "cargo"
# Pass any task args (e.g., --locked) to cargo BEFORE the `--` separator,
# so they don't get forwarded to clippy by mistake in CI.
args = ["clippy", "${@}", "--", "--no-deps", "-Dwarnings"]

[tasks.test-ci]
run_task = "test"
