# Configuration with selective inputs - only payment service protos
[tool.python_proto_importer]
backend = "protoc"
python_exe = ".venv/bin/python"
include = ["."]
inputs = ["proto/payment/**/*.proto"]
out = "generated/selective_inputs"
mypy = false
mypy_grpc = false
postprocess = { relative_imports = true, fix_pyi = false, create_package = true, exclude_google = true, pyright_header = false }
