# Configuration with empty include - should use default behavior
[tool.python_proto_importer]
backend = "protoc"
python_exe = ".venv/bin/python"
include = []                                                                                                                     # Empty include - test default behavior
inputs = ["proto/**/*.proto"]
out = "generated/empty_include"
mypy = false
mypy_grpc = false
postprocess = { relative_imports = true, fix_pyi = false, create_package = true, exclude_google = true, pyright_header = false }
