# Configuration with alternative proto directory structure
[tool.python_proto_importer]
backend = "protoc"
python_exe = ".venv/bin/python"
include = ["proto_alt/services"]
inputs = ["proto_alt/**/*.proto"]
out = "generated/alt_structure"
mypy = false
mypy_grpc = false
postprocess = { relative_imports = true, fix_pyi = false, create_package = true, exclude_google = true, pyright_header = false }
