name: Release PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    name: Build wheels and publish to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: manylinux2014
          - os: ubuntu-22.04
            target: musllinux_1_2
          - os: macos-14
            target: macos
          - os: windows-2022
            target: windows

    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python (for metadata tools)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build wheels (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          manylinux: ${{ matrix.target == 'musllinux_1_2' && 'musllinux_1_2' || 'manylinux2014' }}
          args: >-
            build --release --features python

      - name: Build wheels (macOS)
        if: ${{ runner.os == 'macOS' }}
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          args: >-
            build --release --features python

      - name: Build wheels (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          args: >-
            build --release --features python

      - name: Build sdist (once)
        if: ${{ runner.os == 'Linux' && matrix.target == 'manylinux2014' }}
        run: |
          uv run maturin sdist

      - name: Publish to PyPI
        if: ${{ env.PYPI_API_TOKEN != '' }}
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv run maturin upload --skip-existing target/wheels/*
